stages:
  - frontend-tests
  - test-deployment

frontend-tests:
  stage: frontend-tests
  script:
    - npm install
    - npm run test

test-deployment:
  stage: test-deployment
  script:
    - npm run build
    - serve -s build/
