stages:
  - frontend-tests
  - test-deployment

before-script:
  script:
    - npm install

frontend-tests:
  stage: frontend-tests
  script:
    - npm run test

test-deployment:
  stage: test-deployment
  script:
    - npm run build
    - serve -s build/
