stages:
  - frontend-tests
  - test-deployment

variables:
  PORT_NO: 3000

frontend-tests:
  stage: frontend-tests
  script:
    - npm install
    - npm run test

test-deployment:
  stage: test-deployment
  script:
    - echo "Killing old running process."
    - kill -9 $(lsof -t -i:$PORT_NO) || echo "Nothing to kill or kill failed"
    - npm install
    - npm run build
    - export PORT=$PORT_NO
    - serve -s build -l tcp://146.169.41.57:$PORT_NO/
