stages:
  - frontend-tests
  - test-deployment

frontend-tests:
  stage: frontend-tests
  script:
    - npm install
    - npm run test

test-deployment:
  stage: test-deployment
  script:
    - echo "Killing old running process."
    - kill -9 $(lsof -t -i:3000) || echo "Nothing to kill or kill failed"
    - npm install
    - npm run build
    - serve -s build -l tcp://146.169.41.57:3000/
